#!/bin/bash

toMsys2Format() {
    REP_C=${1//C:/\/c}
    REP_D=${REP_C//D:/\/d}
    REP_SEP=${REP_D//\\/\/}
    echo ${REP_SEP}
}

SNAPSHOT_PKG_DB=$(toMsys2Format "$(stack path --snapshot-pkg-db)")
LOCAL_PKG_DB=$(toMsys2Format "$(stack path --local-pkg-db)")
BIN_PATH=$(toMsys2Format "$(stack path --bin-path)")

export PATH=${BIN_PATH}
export LANG=C

cabal configure \
    --package-db=clear \
    --package-db=global \
    --package-db=${SNAPSHOT_PKG_DB} \
    --package-db=${LOCAL_PKG_DB}

