#!/bin/bash

SNAPSHOT_PKG_DB=$(stack path --snapshot-pkg-db)
LOCAL_PKG_DB=$(stack path --local-pkg-db)
BIN_PATH=$(stack path --bin-path)

export PATH=${BIN_PATH}

cabal configure \
    --package-db=clear \
    --package-db=global \
    --package-db=${SNAPSHOT_PKG_DB} \
    --package-db=${LOCAL_PKG_DB}

